### PR TITLE
Removed travis CI, not used anymore, using github actions CI

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by SodaqMoja** [comment]
Thanks. So does that mean we can get rid of `.travis.yml` in our repos as well?

**Comment by jwillemsen** [comment]
In order to use travis-ci you have to manually setup that, github actions are faster and easier to use. Most travis files in the sodaq repostories are old and don’t seem to work currently. At the moment you switch to a project to github actions I would be in favor of removing travis. There is also a gitlab file but I think you use that internally, correct?

**Comment by SodaqMoja** [comment]
Yes, we use GitLab internally. It's not ideal, I can tell you.

**Comment by jwillemsen** [comment]
I will try to convert some more repositories to use github actions, including the usage of arduino in addition to platformio

**Pull request merged**
